### ISSUE TITLE
Key events not working

### ISSUE THREAD

**Issue by stridervc** [JoelOtter/termloop#7]
Having a weird issue.
I'm trying the examples on Linux. With collision.go, key events work. Esc exits, arrow keys move.
With movingtext.go however, I cannot exit with Esc, and arrow keys don't work. I'm also going through the tutorial, and there Esc doesn't exit either. It's as if the Entity's Tick never gets called.

**Comment by JoelOtter** [comment]
That does sound quite weird - I'm not quite sure what to suggest. Would you mind providing me with some more information? For example:

- Which Linux distribution you're using
- Which terminal emulator you're using
- Which version of Go you have installed

**Comment by stridervc** [comment]
I'm using
* Fedora 17 (A bit old)
* gnome-terminal 3.4.1.1
* Go 1.1.1

I've also tested in xterm on this machine and got the same issue.

**Comment by JoelOtter** [comment]
I think the culprit here is most likely to be your version of Go - 1.1.1 is over two years old, and the way Goroutines are handled internally may have changed. Termloop uses Goroutines to process events concurrently so this might be the cause of your issue.

Can you try it with a newer Go version? I've tested it on Ubuntu 14.04/GNOME Terminal 3.6.2/Go 1.4.2 and it's worked fine.

**Comment by stridervc** [comment]
Ok, thanks, I'll try that. I'll close the issue since that does seem very likely to be the solution.
